# Copyright 2021 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

dbt_airflow_on_gcp:
  target: local
  outputs:
    local:
      type: bigquery
      method: oauth
      project: "{{ var('project_id') }}"
      schema: dev
      threads: 2
      timeout_seconds: 10
      location: "{{ var('bigquery_location') }}"
      priority: batch
      retries: 0

    remote:
      type: bigquery
      method: service-account
      project: "{{ var('project_id') }}"
      schema: prod
      threads: 10
      keyfile: "{{ var('key_file_dir') }}"
      timeout_seconds: 300
      location: "{{ var('bigquery_location') }}"
      priority: batch
      retries: 5

    cloud-build:
      type: bigquery
      method: oauth
      project: "{{ var('project_id') }}"
      schema: dev
      threads: 2
      timeout_seconds: 10
      location: "{{ var('bigquery_location') }}"
      priority: batch
      retries: 0
      impersonate_service_account: "{{ var('impersonate_service_account') }}"