#   Copyright 2022 Google LLC
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.
default:
  image:
    name: mcr.microsoft.com/dotnet/sdk:5.0
  before_script:
    - apt-get update
    - apt-get install -y make zip msitools wixl
    
variables:
  VERSION: 1.1.0

stages:
  - build
  
build-linux:
  stage: build
  script:
    - make linux-x64
  only:
    - main
    - merge_requests
  tags:
    - cloud
  artifacts:
    paths:
      - bin/gsnapshot-${VERSION}-linux-x64.tar.gz

build-osx:
  stage: build
  script:
    - make osx-x64
  only:
    - main
    - merge_requests
  tags:
    - cloud
  artifacts:
    paths:
      - bin/gsnapshot-${VERSION}-osx-x64.tar.gz

build-windows:
  stage: build
  script:
    - make win-x64
    - make win-x86
  only:
    - main
    - merge_requests
  tags:
    - cloud
  artifacts:
    paths:
      - bin/gsnapshot-${VERSION}-x64.msi
      - bin/gsnapshot-${VERSION}-x86.msi

